version: '3'
services:
  hastalavista:
    build: .
    ports:
      - "8080:80"
    environment:
      AWS_REGION: "us-east-1"
      LOGLEVEL: "debug"
      SECRET: "abcd"
      CLOUDPROVIDER: "aws"
