{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
{{- if .Values.ingress.extraAnnotations }}
{{ toYaml .Values.ingress.extraAnnotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "fullname" . }}
    component: app-ingress
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- with .Values.ingress.extraLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.enableTLS}}
  tls:
  - hosts:
    - "{{ .Values.ingress.host }}"
    secretName: {{ .Values.ingress.tlsSecretName }}
{{- end }}
  rules:
  - host: "{{ .Values.hostname }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.inboundPort }}
{{- end -}}
